import {
  BadRequestException,
  Body,
  Controller,
  Get,
  Headers,
  Inject,
  Param,
  ParseIntPipe,
  ParseUUIDPipe,
  Post,
  Query,
  forwardRef,
} from '@nestjs/common';
import { PayrollInitService } from './payroll-init.service';
import { TaskService } from '../task/task.service';
import { TaskEmployeeBreakdownService } from '../task/task-employee-breakdown.service';
import { TaskPayrollHistoryService } from '../task/task-payroll-history.service';
import type { ReportTaskUnitInput } from '../task/task.types';
import { InvoiceAuthService } from '../invoice/invoice-auth.service';
import { CapabilityService } from '../capabilities/capability.service';
import { ExecutionIntentService } from '../execution-intent/execution-intent.service';
import { PayrollReceiptVerifierService } from '../task/payroll-receipt-verifier.service';
import { parseUnits } from 'viem';

@Controller('tasks')
export class TaskController {
  constructor(
    private readonly taskService: TaskService,
    @Inject(forwardRef(() => TaskEmployeeBreakdownService))
    private readonly taskEmployeeBreakdownService: TaskEmployeeBreakdownService,
    private readonly taskPayrollHistoryService: TaskPayrollHistoryService,
    private readonly payrollInitService: PayrollInitService,
    private readonly invoiceAuthService: InvoiceAuthService,
    private readonly capabilities: CapabilityService,
    private readonly intents: ExecutionIntentService,
    private readonly payrollReceipts: PayrollReceiptVerifierService,
  ) {}

  /**
   * POST /tasks/payroll/init — Validate and batch a payroll run before execution.
   *
   * Frontend sends the current payroll draft and receives a normalized plan
   * generated by backend payroll services. This keeps validation, batching,
   * and reference-id expansion in one place before any wallet confirmation.
   */
  @Post('payroll/init')
  async initPayroll(@Body() payload: Record<string, unknown>) {
    this.capabilities.assertPayroll(payload ?? {});
    return {
      data: await this.payrollInitService.prepare(payload ?? {}),
    };
  }

  @Post('liquidity/init')
  async initLiquidity(@Body() payload: Record<string, unknown>) {
    return {
      data: await this.taskService.createLiquidityTask(payload ?? {}),
    };
  }

  @Post(':taskId/units/:unitId/report')
  async reportTaskUnit(
    @Param('taskId', new ParseUUIDPipe()) taskId: string,
    @Param('unitId', new ParseUUIDPipe()) unitId: string,
    @Body() body: ReportTaskUnitInput,
  ) {
    this.capabilities.assert('sameTokenPayroll');
    if (body.status === 'SUCCESS') {
      const task = await this.taskService.getTaskById(taskId);
      const unit = task.units.find((candidate) => candidate.id === unitId);
      if (!unit || !body.txHash || !body.executionIntentId)
        throw new BadRequestException({
          code: 'PAYROLL_EXECUTION_INTENT_REQUIRED',
          message:
            'Successful payroll reporting requires its durable intent and transaction hash.',
        });
      const intent = await this.intents.get(body.executionIntentId);
      const payload = unit.payload;
      if (
        intent.taskId !== taskId ||
        intent.externalReference !== payload.referenceId
      )
        throw new BadRequestException({
          code: 'EXECUTION_INTENT_IMMUTABLE_CONFLICT',
          message: 'Payroll unit does not match its durable execution intent.',
        });
      await this.intents.bindTransactionHash(intent.id, body.txHash);
      await this.intents.beginVerification(intent.id);
      await this.payrollReceipts.verify({
        transactionHash: body.txHash,
        sourceWallet: intent.sourceWallet,
        token: intent.tokenOut,
        totalAmountUnits: intent.amountUnits,
        referenceId: String(payload.referenceId ?? ''),
        recipients: Array.isArray(payload.recipients)
          ? (payload.recipients as Record<string, unknown>[]).map(
              (recipient) => ({
                address: String(recipient.address ?? ''),
                amountUnits:
                  typeof recipient.amountUnits === 'string'
                    ? recipient.amountUnits
                    : parseUnits(String(recipient.amount ?? ''), 6).toString(),
              }),
            )
          : [],
      });
      await this.intents.completeWithVerifiedReceipt(intent.id, {
        network: intent.network,
        transactionHash: body.txHash as `0x${string}`,
        sourceWallet: intent.sourceWallet,
        token: intent.tokenOut,
        batchDigest: intent.batchDigest,
        amountUnits: intent.amountUnits,
      });
    }
    return {
      data: await this.taskService.reportUnit(taskId, unitId, body),
    };
  }

  /**
   * GET /tasks — List tasks owned by the authenticated Circle user.
   *
   * Query params:
   *   type       — filter by task type (payroll, swap, bridge, liquidity, fx)
   *   status     — filter by status (executed, failed, in_progress, …)
   *   limit      — max results (default 50, max 200)
   *   offset     — pagination offset (default 0)
   */
  @Get()
  async listTasks(
    @Headers('authorization') authorization?: string,
    @Query('type') type?: string,
    @Query('status') status?: string,
    @Query('limit', new ParseIntPipe({ optional: true })) limit?: number,
    @Query('offset', new ParseIntPipe({ optional: true })) offset?: number,
  ) {
    const principal = await this.invoiceAuthService.authenticate(authorization);

    return {
      data: await this.taskService.getTaskList({
        type,
        status,
        walletAddress: principal.merchantWalletAddress,
        limit,
        offset,
      }),
    };
  }

  /**
   * GET /tasks/payroll/history?wallet=0x... — Wallet-scoped payroll history.
   *
   * Returns confirmed payroll batch events and employee-level payments using
   * backend chain reads so overview cards and recent payroll tables do not
   * scan logs in the browser. Includes legacy contract coverage.
   */
  @Get('payroll/history')
  async getPayrollHistory(@Query('wallet') walletAddress?: string) {
    return {
      data: await this.taskPayrollHistoryService.getWalletPayrollHistory(
        walletAddress,
      ),
    };
  }

  /**
   * GET /tasks/:id — Poll task status.
   *
   * Frontend polls this endpoint to track progress.
   * Returns the full task with logs only to its authenticated canonical owner.
   */
  @Get(':id')
  async getTask(
    @Param('id', new ParseUUIDPipe()) id: string,
    @Headers('authorization') authorization?: string,
  ) {
    const principal = await this.invoiceAuthService.authenticate(authorization);

    return {
      data: await this.taskService.getOwnedTaskById(
        id,
        principal.merchantWalletAddress,
      ),
    };
  }

  /**
   * GET /tasks/:id/employee-breakdown — Return confirmed employee-level payroll payments.
   *
   * Frontend uses this endpoint to render owned payroll rows without scanning
   * chain logs or transaction receipts in the browser.
   */
  @Get(':id/employee-breakdown')
  async getEmployeeBreakdown(
    @Param('id', new ParseUUIDPipe()) id: string,
    @Headers('authorization') authorization?: string,
  ) {
    const principal = await this.invoiceAuthService.authenticate(authorization);

    return {
      data: await this.taskEmployeeBreakdownService.getPayrollEmployeeBreakdown(
        id,
        principal.merchantWalletAddress,
      ),
    };
  }
}
