import {
  Body,
  Controller,
  Get,
  Inject,
  Param,
  ParseIntPipe,
  ParseUUIDPipe,
  Post,
  Query,
  forwardRef,
} from '@nestjs/common';
import { PayrollInitService } from './payroll-init.service';
import { TaskService } from '../task/task.service';
import { TaskEmployeeBreakdownService } from '../task/task-employee-breakdown.service';
import { TaskPayrollHistoryService } from '../task/task-payroll-history.service';
import type { ReportTaskUnitInput } from '../task/task.types';

@Controller('tasks')
export class TaskController {
  constructor(
    private readonly taskService: TaskService,
    @Inject(forwardRef(() => TaskEmployeeBreakdownService))
    private readonly taskEmployeeBreakdownService: TaskEmployeeBreakdownService,
    private readonly taskPayrollHistoryService: TaskPayrollHistoryService,
    private readonly payrollInitService: PayrollInitService,
  ) {}

  /**
   * POST /tasks/payroll/init — Validate and batch a payroll run before execution.
   *
   * Frontend sends the current payroll draft and receives a normalized plan
   * generated by backend payroll services. This keeps validation, batching,
   * and reference-id expansion in one place before any wallet confirmation.
   */
  @Post('payroll/init')
  async initPayroll(@Body() payload: Record<string, unknown>) {
    return {
      data: await this.payrollInitService.prepare(payload ?? {}),
    };
  }

  @Post('liquidity/init')
  async initLiquidity(@Body() payload: Record<string, unknown>) {
    return {
      data: await this.taskService.createLiquidityTask(payload ?? {}),
    };
  }

  @Post(':taskId/units/:unitId/report')
  async reportTaskUnit(
    @Param('taskId', new ParseUUIDPipe()) taskId: string,
    @Param('unitId', new ParseUUIDPipe()) unitId: string,
    @Body() body: ReportTaskUnitInput,
  ) {
    return {
      data: await this.taskService.reportUnit(taskId, unitId, body),
    };
  }

  /**
   * GET /tasks — List tasks with optional filters.
   *
   * Query params:
   *   type       — filter by task type (payroll, swap, bridge, liquidity, fx)
   *   status     — filter by status (executed, failed, in_progress, …)
   *   wallet     — filter by wallet/recipient address stored in metadata
   *   limit      — max results (default 50, max 200)
   *   offset     — pagination offset (default 0)
   */
  @Get()
  async listTasks(
    @Query('type') type?: string,
    @Query('status') status?: string,
    @Query('wallet') walletAddress?: string,
    @Query('limit', new ParseIntPipe({ optional: true })) limit?: number,
    @Query('offset', new ParseIntPipe({ optional: true })) offset?: number,
  ) {
    return {
      data: await this.taskService.getTaskList({
        type,
        status,
        walletAddress,
        limit,
        offset,
      }),
    };
  }

  /**
   * GET /tasks/payroll/history?wallet=0x... — Wallet-scoped payroll history.
   *
   * Returns confirmed payroll batch events and employee-level payments using
   * backend chain reads so overview cards and recent payroll tables do not
   * scan logs in the browser. Includes legacy contract coverage.
   */
  @Get('payroll/history')
  async getPayrollHistory(@Query('wallet') walletAddress?: string) {
    return {
      data: await this.taskPayrollHistoryService.getWalletPayrollHistory(
        walletAddress,
      ),
    };
  }

  /**
   * GET /tasks/:id — Poll task status.
   *
   * Frontend polls this endpoint to track progress.
   * Returns the full task with logs for fine-grained progress display.
   */
  @Get(':id')
  async getTask(@Param('id', new ParseUUIDPipe()) id: string) {
    return {
      data: await this.taskService.getTaskById(id),
    };
  }

  /**
   * GET /tasks/:id/employee-breakdown — Return confirmed employee-level payroll payments.
   *
   * Frontend uses this endpoint to render recent payroll rows without scanning
   * chain logs or transaction receipts in the browser.
   */
  @Get(':id/employee-breakdown')
  async getEmployeeBreakdown(@Param('id', new ParseUUIDPipe()) id: string) {
    return {
      data: await this.taskEmployeeBreakdownService.getPayrollEmployeeBreakdown(
        id,
      ),
    };
  }
}
