import {
  Body,
  Controller,
  Get,
  Param,
  ParseUUIDPipe,
  Post,
  UsePipes,
  ValidationPipe,
} from '@nestjs/common';
import { OrchestratorService } from './orchestrator.service';
import { PayrollInitService } from './payroll-init.service';
import { CreateTaskDto } from '../task/dto/create-task.dto';
import { TaskService } from '../task/task.service';

@Controller('tasks')
export class TaskController {
  constructor(
    private readonly orchestratorService: OrchestratorService,
    private readonly taskService: TaskService,
    private readonly payrollInitService: PayrollInitService,
  ) {}

  /**
   * POST /tasks/payroll/init — Validate and batch a payroll run before execution.
   *
   * Frontend sends the current payroll draft and receives a normalized plan
   * generated by backend payroll services. This keeps validation, batching,
   * and reference-id expansion in one place before any wallet confirmation.
   */
  @Post('payroll/init')
  async initPayroll(@Body() payload: Record<string, unknown>) {
    return {
      data: await this.payrollInitService.prepare(payload ?? {}),
    };
  }

  /**
   * POST /tasks — Create and enqueue a new task.
   *
   * This is the ONLY entry point for frontend task submission.
   * Frontend sends:
   *   { "type": "payroll", "payload": { ... } }
   *
   * Backend handles:
   *   - DTO validation (class-validator)
   *   - Task creation + state machine
   *   - Queue routing + agent execution
   */
  @Post()
  @UsePipes(
    new ValidationPipe({
      whitelist: true,
      forbidNonWhitelisted: true,
      transform: true,
    }),
  )
  async createTask(@Body() body: CreateTaskDto) {
    return {
      data: await this.orchestratorService.handleTask(
        body.type,
        body.payload ?? {},
      ),
    };
  }

  /**
   * GET /tasks/:id — Poll task status.
   *
   * Frontend polls this endpoint to track progress.
   * Returns the full task with logs for fine-grained progress display.
   */
  @Get(':id')
  async getTask(@Param('id', new ParseUUIDPipe()) id: string) {
    return {
      data: await this.taskService.getTaskById(id),
    };
  }
}
